language: bash

before_install:
  - git clone https://github.com/hmngwy/jenny.git /tmp/jenny
  - (cd /tmp/jenny; sudo make install)
  - mkdir .dist

script:
  - jenny -c -v -n

deploy:
  provider: pages
  local_dir: .dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
  on:
    branch: master
